---
- hosts: all
  remote_user: root
  vars_prompt:
    - name: rpcusername
      prompt: 'rpcuser for bitcoin daemon'
      private: no
    - name: rpcpassword
      prompt: 'rpcpassword for bitcoin daemon'
      private: yes


  tasks:
  - name: install required tools
    yum: pkg=python-setuptools state=latest
    yum: pkg=git-core state=latest
    yum: pkg=openssl-devel state=latest
    yum: pkg=python-devel state=latest


  - name: install ringingliberty repo for bitcoind
    shell: rpm -Uvh http://linux.ringingliberty.com/bitcoin/el6/x86_64/bitcoin-release-1-4.noarch.rpm creates=/etc/yum.repos.d/bitcoin.repo
    shell: rpm --import http://linux.ringingliberty.com/bitcoin/RPM-GPG-KEY-bitcoin creates=/etc/pki/rpm-gpg/RPM-GPG-KEY-bitcoin
    tags: bitcoind

  - name: install python libs for electrum server
    action: easy_install name={{ item }}
    with_items:
      - jsonrpclib
      - pyopenssl
      - pip
    tags: electrum

  - name: install leveldb for electrum server
    pip: name=leveldb
    tags: electrum

  - name: install bitcoin server (bitcoind)
    yum: pkg=bitcoin-server state=latest
    tags: bitcoind

  - name: configure bitcoind
    template: src=files/bitcoin.conf dest=/etc/bitcoin/bitcoin.conf force=yes backup=yes
    tags: bitcoind

  - name: start bitcoind
    service:
      name: bitcoin
      state: restarted
    tags: bitcoind

  - name: install electrum server
    git: 'repo=https://github.com/spesmilo/electrum-server.git dest=/opt/local/electrum-server'
    tags: electrum

  - name: assign bitcoin user to electrum-server
    file: path=/opt/local/electrum-server owner=bitcoin group=bitcoin state=directory
    file: path=/var/lib/local/electrumdb owner=bitcoin group=bitcoin state=directory
    tags: electrum

  - name: configure electrum server
    template: src=files/electrum.conf dest=/etc/electrum.conf force=yes backup=yes
    tags: electrum

# Next up is to prime the electrum DB with http://foundry.electrum.org/leveldb-dump/electrum-leveldb-100-2013-11-24.tar.bz2
